### ISSUE TITLE
Query: Video Streaming

### ISSUE THREAD

**Issue by jkad123** [rhysmorgan134/SocketMost#22]
Looking at the source, it seems like a lot of the streaming functionality is written with audio streaming in mind (i.e. functions referencing streaming have comments that specifically say "audio"). 

My question is: are these functions all audio-specific, or can I send video streaming data through them? 

My use case is to pretend to be a NAV unit (FBlockID 0x52) on an L322, and send video and audio over MOST. The benefit of this is that you would not need to replace the touchscreen, and you would maintain amplifier functionality.

**Comment by rhysmorgan134** [comment]
MOST25 is not ideal for video streaming, if your L322 is anything like my X250 or L359 then video from the nav unit is done via gvif and not MOST. 

If a vehicle does make use of Video over MOST25 then the driver could implement it, however I am unable to do so as it's not something I currently have access to.

On a side note, touch coordinates on the x250 are sent over MOST, so it is 50% of the way there!

**Comment by jkad123** [comment]
Very interesting! Thanks for your prompt response. Yes I think I remember seeing touch coordinates in the MOST spec.

I'll take a look at the TV tuner module as the presence of gvif connectors on that will likely suggest how it's done.

Thanks again :smile:

**Comment by rhysmorgan134** [comment]
No problem, but similar story to the nav for the tv tuner. 

![image](https://github.com/rhysmorgan134/SocketMost/assets/36861722/e05e0aa9-3f0d-4e07-93b9-5f21dbb7694c)

In this image, the blue connector is for the nav, this is gvif. For tv tuner and reverse camera these actually use standard analog video, and these are the 3 fakra connectors at the top. 

This would be much easier to implement, the Pi etc could send video out as rca, PiMost could hijack the tvtuner address and receive the touch co ordinates. However I suspect the OEM screen will still react to touch points (full screen etc)
